### PR TITLE
Add documentation of kiwi-boxed-plugin usage

### PR DESCRIPTION
**Pull request by kageurufu**

### CODE REVIEW

**Comment by phillxnet** [comment]
@kageurufu Thanks for stepping up to this one. Linking for context to the associated forum thread section:

https://forum.rockstor.com/t/4-0-7-iso-creation/7837/5

From a quick perusal this looks like just the job. Thanks.
You note that 8 GB of RAM is reserved. If this is not available does this method end up thrashing swap on the host system? My concern is to address folks blindly copying and pasting this method on inappropriate hardware and ending up with seemingly endless system thrashing. Thanks for putting in these details by the way. Nice touch.

**Comment by kageurufu** [comment]
Honestly, not a clue. Thats a default in the boxed plugin, so I wanted to make sure people could immediately find the "fix" if they were ram-starved. I'll test on a small VM and see what happens

**Comment by kageurufu** [comment]
It's slow, but i'm able to build using `boxed` constrained to only 2GB and a single core. `36:18.26` using a 8850H on nvme storage.

**Comment by phillxnet** [comment]
@kageurufu Thanks for the testing here. Much appreciated.
Re:

> I'll add a note about ensuring you have enough available RAM.

Cheers. I'll await your edit and then get this one merged. It would be great to have a more linux OS generic approach to these instructions via the kiwi-ng boxbuild method, along with some clear guidelines on it's RAM requirements.

**Comment by kageurufu** [comment]
Sounds good. I've updated the PR, let me know if there's any wording I can clean up, but I think it should be clear enough.

**Comment by phillxnet** [comment]
@kageurufu Thanks. That's a nice addition as often folks will just copy and paste, simply not realise the scope/scale of what they are asking of their machines. In this case the non trivial 8GB RAM, 4 core emulation/virtualisation behind the scenes that is then, in turn, tasked with the non trivial building an entire other OS installer.

I'm going to merge this as-is since I think it's a valuable addition that significantly eases the task at hand.

> ... let me know if there's any wording I can clean up, but I think it should be clear enough.

Agreed. We can always clean up as we go and as you say it's plenty clear enough, and has far more pointers re required hardware (virtual or real) than we had previously. Nice move with moving to an example config for a downgraded KVM spec by the way.

Thanks again for stepping up to this and apologies for my delayed feedback on a number of occasions. But it looks like we got there in the end. Pretty key kiwi-ng feature this so I was chuffed when it came along so it's nice we can now offer a clear and tested example of it's use for our purposes; thanks to your efforts here.

**Pull request merged**
